version: 1

# logging configuration
log:
  # debug, info, warning, error, fatal - default 'info'
  level: debug

app:
  port: 8000

db:
  host: localhost
  port: 5432
  name: kay
  user: kay
  password: kay_password
  sslmode: disable
